### PR TITLE
Implement basic API for component

### LINKED ISSUE #1: It should be possible to create an alert style dialog
It should be possible to create an alert style confirm dialog with OK button

### LINKED ISSUE #3: It should be possible to create 3-way confirm dialog
It should be possible to create 3-way confirm dialog with Yes / No / Cancel buttons.

### LINKED ISSUE #4: It should be possible to customize the dialog texts
- I want to change dialog message text and button texts

### PR DESCRIPTION
**Pull request by alvarezguille**
Add alert use cases to test UI
Fixes #1
Fixes #3
Fixes #4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10#-LEylMeTChL9NFU4rtQ8:-LEylMeU7DgUs1VfyPgr:b-qvg3c5) (no related file):*
WIP
Following is still missing:
* Change magic strings for constants
* Add tests for combination of [use provided components, DIY mode] with [use java API, declare in template] 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10)*

**Comment by johannesh2** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @alvarezguille)

---

*[vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java, line 58 at r1](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10#-LFGrFf86_I5HCCNoSeZ:-LFGrFf90V4LX1N8aUYG:by1ndcs) ([raw file](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/de33af77ff947264d59246b18062711dcd64f07f/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java#L58)):*
> ```Java
> 
>     @DomEvent("cancel")
>     public static class ConfirmDialogCancelEvent
> ```

Instead ConfirmDialogXEvent . Maybe XEvent? Other components don't seem to have Component name in event

---

*[vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java, line 131 at r1](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10#-LFGs0UM0Bob_F8JY-wI:-LFGs0UM0Bob_F8JY-wJ:b-wyn54a) ([raw file](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/de33af77ff947264d59246b18062711dcd64f07f/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java#L131)):*
> ```Java
>     }
> 
>     public void setCancelButton(String buttonText,
> ```

These setXButton should probably call the boolean property true

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10)*

**Comment by johannesh2** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @alvarezguille)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10)*

**Comment by alexberazouski** [comment]
Review status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alvarezguille)

---

*[vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java, line 131 at r1](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10#-LFGs0UM0Bob_F8JY-wI:-LFGs_8J83meVQE7_T4p:bvzngdw) ([raw file](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/de33af77ff947264d59246b18062711dcd64f07f/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java#L131)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

These setXButton should probably call the boolean property true
</blockquote></details>

fixed in PR 11

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/10)*

**Comment by alvarezguille** [comment]
Included in #12

**Comment by alvarezguille** [comment]
Included in #11

**Pull request closed without merging**
