### PR TITLE
Add module for testbench API

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18)

### CODE REVIEW

**Comment by alexberazouski** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @alvarezguille)

---

*[vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java, line 29 at r1](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18#-LFv_xVY5RVMyLmzxl78:-LFv_xVY5RVMyLmzxl79:bt7uxot) ([raw file](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/154bb319a6748b24319c96aff1f5819c340b0d5f/vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java#L29)):*
> ```Java
> 
>     private TestBenchElement getOverlayContext() {
>         return $("vaadin-dialog-overlay").onPage().first().$(TestBenchElement.class).id("content");
> ```

Could we change first to last as a part of this PR?

---

*[vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java, line 53 at r1](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18#-LFva4I0AanB-F45UedY:-LFva4I0AanB-F45UedZ:b-nspkbu) ([raw file](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/154bb319a6748b24319c96aff1f5819c340b0d5f/vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java#L53)):*
> ```Java
>         return getButton("cancel", "cancel-button");
>     }
> }
> ```

neat pick: let's add the empty line. The same in couple of other files

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18)*

**Comment by alvarezguille** [comment]
Review status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @alexberazouski and @alvarezguille)

---

*[vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java, line 29 at r1](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18#-LFv_xVY5RVMyLmzxl78:-LFvm1im5TJpCiyQvWYp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/154bb319a6748b24319c96aff1f5819c340b0d5f/vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java#L29)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

Could we change first to last as a part of this PR?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @alexberazouski)

---

*[vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java, line 53 at r1](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18#-LFva4I0AanB-F45UedY:-LFvm4DSAeWbLmdaPwU9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/154bb319a6748b24319c96aff1f5819c340b0d5f/vaadin-confirm-dialog-testbench/src/main/java/com/vaadin/flow/component/confirmdialog/testbench/ConfirmDialogElement.java#L53)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

neat pick: let's add the empty line. The same in couple of other files
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18)*

**Comment by alexberazouski** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-confirm-dialog-flow/18#-:-LFvmHAh7lFy6EZocp1Q:bnfp4nl)*

**Pull request merged**
